/**
 * Stable, machine-readable error codes. These are a contract with clients
 * (tenant-web's AuthErrorCode mirrors this list) — never rename an
 * existing code, only add new ones.
 */
export const ErrorCode = {
  // Validation / generic
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // Tenant resolution
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  TENANT_SUSPENDED: 'TENANT_SUSPENDED',
  TRIAL_EXPIRED: 'TRIAL_EXPIRED',
  SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED',
  MAINTENANCE: 'MAINTENANCE',
  SLUG_TAKEN: 'SLUG_TAKEN',
  SLUG_RESERVED: 'SLUG_RESERVED',

  // Authentication
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  EMAIL_ALREADY_VERIFIED: 'EMAIL_ALREADY_VERIFIED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_REUSE_DETECTED: 'TOKEN_REUSE_DETECTED',
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_MAX_ATTEMPTS: 'OTP_MAX_ATTEMPTS',
  UNAUTHENTICATED: 'UNAUTHENTICATED',

  // Authorization
  FORBIDDEN: 'FORBIDDEN',

  // Billing (Prompt 8)
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  COUPON_INVALID: 'COUPON_INVALID',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
